"""add logo_url

Revision ID: 65415b0a6ae3
Revises: rfid001
Create Date: 2026-07-16 15:35:33.347358

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65415b0a6ae3'
down_revision: Union[str, None] = 'rfid001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True, comment='URL del logo de la empresa'))
    op.alter_column('docks', 'dock_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='receiving | shipping | both')
    op.alter_column('docks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='available | occupied | maintenance | blocked')
    op.alter_column('docks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('docks', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('docks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('docks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('docks', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('docks', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('docks', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('docks', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('docks', 'tenant_id',
               existing_type=sa.UUID(),
               comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('labor_standards', 'warehouse_id',
               existing_type=sa.UUID(),
               comment='Bodega a la que aplica. NULL = aplica a todo el tenant.',
               existing_nullable=True)
    op.alter_column('labor_standards', 'activity_type',
               existing_type=sa.VARCHAR(length=20),
               comment='pick | putaway | receive | pack | cycle_count | replenish | loading | unloading | transfer',
               existing_nullable=False)
    op.alter_column('labor_standards', 'uom',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='Unidad de medida del estándar: unit | line | case | pallet')
    op.alter_column('labor_standards', 'fixed_minutes',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False,
               comment='Tiempo fijo de preparación/desplazamiento por tarea (minutos).')
    op.alter_column('labor_standards', 'std_minutes_per_unit',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False,
               comment='Tiempo estándar por unidad de trabajo (minutos).')
    op.alter_column('labor_standards', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('labor_standards', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('labor_standards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('labor_standards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('labor_standards', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('labor_standards', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('labor_standards', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('labor_standards', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('labor_standards', 'tenant_id',
               existing_type=sa.UUID(),
               comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('labor_tasks', 'user_id',
               existing_type=sa.UUID(),
               comment='Operario asignado. NULL mientras la tarea está en cola.',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'reference_type',
               existing_type=sa.VARCHAR(length=30),
               comment='picking_task | putaway_task | grn | cycle_count | ...',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'zone',
               existing_type=sa.VARCHAR(length=50),
               comment='Código de zona para agrupar por proximidad.',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'priority',
               existing_type=sa.NUMERIC(precision=4, scale=0),
               nullable=False,
               comment='1 = más urgente … 9 = menos urgente.')
    op.alter_column('labor_tasks', 'quantity',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=False,
               comment='Unidades de trabajo (según uom del estándar).')
    op.alter_column('labor_tasks', 'uom',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('labor_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='pending | assigned | in_progress | completed | cancelled')
    op.alter_column('labor_tasks', 'actual_minutes',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Tiempo real trabajado (completed_at - started_at).',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'standard_minutes',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='Tiempo esperado según el estándar de ingeniería.',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'performance_pct',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               comment='standard/actual*100. 100 = cumple; >100 más rápido; <100 más lento.',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'is_interleaved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='True si la tarea fue asignada por el motor de interleaving.')
    op.alter_column('labor_tasks', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('labor_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('labor_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('labor_tasks', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'tenant_id',
               existing_type=sa.UUID(),
               comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.create_index(op.f('ix_labor_tasks_status'), 'labor_tasks', ['status'], unique=False)
    op.alter_column('rfid_antennas', 'antenna_number',
               existing_type=sa.INTEGER(),
               comment='Número de puerto físico en el reader (1-N).',
               existing_nullable=False)
    op.alter_column('rfid_antennas', 'location_id',
               existing_type=sa.UUID(),
               comment='Ubicación física que cubre esta antena (dock door, frente de picking, etc).',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'transmit_power_dbm',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Potencia de transmisión configurada (dBm).',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('rfid_antennas', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('rfid_antennas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_antennas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_antennas', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'tenant_id',
               existing_type=sa.UUID(),
               comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('rfid_readers', 'code',
               existing_type=sa.VARCHAR(length=30),
               comment='Código interno único por bodega.',
               existing_nullable=False)
    op.alter_column('rfid_readers', 'vendor',
               existing_type=sa.VARCHAR(length=30),
               comment='zebra | impinj | honeywell | alien | otro',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'port',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Puerto LLRP (5084 = default EPCglobal).',
               existing_nullable=False)
    op.alter_column('rfid_readers', 'protocol',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('rfid_readers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='active | inactive | offline',
               existing_nullable=False)
    op.alter_column('rfid_readers', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Último heartbeat/lectura recibida del gateway LLRP.',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('rfid_readers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_readers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_readers', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'tenant_id',
               existing_type=sa.UUID(),
               comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('rfid_tag_reads', 'epc_hex',
               existing_type=sa.VARCHAR(length=24),
               comment='EPC crudo leído del tag (24 hex = 96 bits).',
               existing_nullable=False)
    op.alter_column('rfid_tag_reads', 'epc_scheme',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment='sgtin96 | sscc96 | unknown',
               existing_nullable=False)
    op.alter_column('rfid_tag_reads', 'product_id',
               existing_type=sa.UUID(),
               comment='Producto resuelto por GTIN (si el EPC es SGTIN-96 y el GTIN existe en el catálogo).',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'rssi_dbm',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment='Intensidad de señal reportada por el reader (dBm).',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'processed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('rfid_tag_reads', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('rfid_tag_reads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_tag_reads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_tag_reads', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'tenant_id',
               existing_type=sa.UUID(),
               comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.create_index(op.f('ix_rfid_tag_reads_warehouse_id'), 'rfid_tag_reads', ['warehouse_id'], unique=False)
    op.alter_column('slotting_policies', 'warehouse_id',
               existing_type=sa.UUID(),
               comment='Bodega a la que aplica. NULL = política global del tenant.',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'strategy',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='velocity_abc | manual')
    op.alter_column('slotting_policies', 'velocity_window_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Ventana (días) de movimientos usada para medir rotación.')
    op.alter_column('slotting_policies', 'abc_a_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               comment='Cuota acumulada de velocidad que define la clase A (p. ej. 0.80).')
    op.alter_column('slotting_policies', 'abc_b_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=False,
               comment='Cuota acumulada que define hasta la clase B (p. ej. 0.95).')
    op.alter_column('slotting_policies', 'golden_zone_code',
               existing_type=sa.VARCHAR(length=10),
               comment='Código de zona dorada (frente de picking más cercano).',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'bulk_zone_code',
               existing_type=sa.VARCHAR(length=10),
               comment='Código de zona de bulk/reserva para baja rotación (C).',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('slotting_policies', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('slotting_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('slotting_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('slotting_policies', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'tenant_id',
               existing_type=sa.UUID(),
               comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('slotting_recommendations', 'abc_class',
               existing_type=sa.VARCHAR(length=1),
               comment='A | B | C',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'score_delta',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Mejora estimada (proxy de ahorro de recorrido).',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='pending | applied | rejected | expired')
    op.alter_column('slotting_recommendations', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('slotting_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('slotting_recommendations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('slotting_recommendations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'tenant_id',
               existing_type=sa.UUID(),
               comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.create_index(op.f('ix_slotting_recommendations_status'), 'slotting_recommendations', ['status'], unique=False)
    op.alter_column('warehouses', 'picking_strategy',
               existing_type=sa.VARCHAR(length=20),
               comment='Estrategia de rotacion de inventario: FEFO | FIFO | LIFO',
               existing_comment='Estrategia de picking: FEFO | FIFO | LIFO',
               existing_nullable=False)
    op.alter_column('warehouses', 'default_picking_method',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='Metodo de picking por defecto al crear una Wave: discrete | batch | zone | cluster (ver PickingMethod en models/outbound.py)',
               existing_comment='Metodo de picking por defecto al crear una Wave: discrete | batch | zone | cluster',
               existing_nullable=False)
    op.alter_column('yard_appointments', 'appointment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='inbound | outbound')
    op.alter_column('yard_appointments', 'reference',
               existing_type=sa.VARCHAR(length=100),
               comment='Número de ASN/SO asociado',
               existing_nullable=True)
    op.alter_column('yard_appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='scheduled | arrived | at_dock | departed | cancelled | no_show')
    op.alter_column('yard_appointments', 'id',
               existing_type=sa.UUID(),
               comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('yard_appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('yard_appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('yard_appointments', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('yard_appointments', 'deleted_by',
               existing_type=sa.UUID(),
               comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('yard_appointments', 'created_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('yard_appointments', 'updated_by',
               existing_type=sa.UUID(),
               comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('yard_appointments', 'tenant_id',
               existing_type=sa.UUID(),
               comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('yard_appointments', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('yard_appointments', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('yard_appointments', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('yard_appointments', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('yard_appointments', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('yard_appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('yard_appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('yard_appointments', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('yard_appointments', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='scheduled | arrived | at_dock | departed | cancelled | no_show')
    op.alter_column('yard_appointments', 'reference',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Número de ASN/SO asociado',
               existing_nullable=True)
    op.alter_column('yard_appointments', 'appointment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='inbound | outbound')
    op.alter_column('warehouses', 'default_picking_method',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'discrete'::character varying"),
               comment='Metodo de picking por defecto al crear una Wave: discrete | batch | zone | cluster',
               existing_comment='Metodo de picking por defecto al crear una Wave: discrete | batch | zone | cluster (ver PickingMethod en models/outbound.py)',
               existing_nullable=False)
    op.alter_column('warehouses', 'picking_strategy',
               existing_type=sa.VARCHAR(length=20),
               comment='Estrategia de picking: FEFO | FIFO | LIFO',
               existing_comment='Estrategia de rotacion de inventario: FEFO | FIFO | LIFO',
               existing_nullable=False)
    op.drop_index(op.f('ix_slotting_recommendations_status'), table_name='slotting_recommendations')
    op.alter_column('slotting_recommendations', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('slotting_recommendations', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('slotting_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('slotting_recommendations', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('slotting_recommendations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='pending | applied | rejected | expired')
    op.alter_column('slotting_recommendations', 'score_delta',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Mejora estimada (proxy de ahorro de recorrido).',
               existing_nullable=True)
    op.alter_column('slotting_recommendations', 'abc_class',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='A | B | C',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('slotting_policies', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('slotting_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('slotting_policies', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('slotting_policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('slotting_policies', 'bulk_zone_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Código de zona de bulk/reserva para baja rotación (C).',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'golden_zone_code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Código de zona dorada (frente de picking más cercano).',
               existing_nullable=True)
    op.alter_column('slotting_policies', 'abc_b_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               comment=None,
               existing_comment='Cuota acumulada que define hasta la clase B (p. ej. 0.95).')
    op.alter_column('slotting_policies', 'abc_a_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               nullable=True,
               comment=None,
               existing_comment='Cuota acumulada de velocidad que define la clase A (p. ej. 0.80).')
    op.alter_column('slotting_policies', 'velocity_window_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Ventana (días) de movimientos usada para medir rotación.')
    op.alter_column('slotting_policies', 'strategy',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='velocity_abc | manual')
    op.alter_column('slotting_policies', 'warehouse_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Bodega a la que aplica. NULL = política global del tenant.',
               existing_nullable=True)
    op.drop_index(op.f('ix_rfid_tag_reads_warehouse_id'), table_name='rfid_tag_reads')
    op.alter_column('rfid_tag_reads', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('rfid_tag_reads', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_tag_reads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_tag_reads', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('rfid_tag_reads', 'processed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('rfid_tag_reads', 'rssi_dbm',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               comment=None,
               existing_comment='Intensidad de señal reportada por el reader (dBm).',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'product_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Producto resuelto por GTIN (si el EPC es SGTIN-96 y el GTIN existe en el catálogo).',
               existing_nullable=True)
    op.alter_column('rfid_tag_reads', 'epc_scheme',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'unknown'::character varying"),
               comment=None,
               existing_comment='sgtin96 | sscc96 | unknown',
               existing_nullable=False)
    op.alter_column('rfid_tag_reads', 'epc_hex',
               existing_type=sa.VARCHAR(length=24),
               comment=None,
               existing_comment='EPC crudo leído del tag (24 hex = 96 bits).',
               existing_nullable=False)
    op.alter_column('rfid_readers', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('rfid_readers', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_readers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_readers', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('rfid_readers', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Último heartbeat/lectura recibida del gateway LLRP.',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'inactive'::character varying"),
               comment=None,
               existing_comment='active | inactive | offline',
               existing_nullable=False)
    op.alter_column('rfid_readers', 'protocol',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'LLRP'::character varying"),
               existing_nullable=False)
    op.alter_column('rfid_readers', 'port',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5084'),
               comment=None,
               existing_comment='Puerto LLRP (5084 = default EPCglobal).',
               existing_nullable=False)
    op.alter_column('rfid_readers', 'vendor',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='zebra | impinj | honeywell | alien | otro',
               existing_nullable=True)
    op.alter_column('rfid_readers', 'code',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='Código interno único por bodega.',
               existing_nullable=False)
    op.alter_column('rfid_antennas', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('rfid_antennas', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_antennas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rfid_antennas', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('rfid_antennas', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('rfid_antennas', 'transmit_power_dbm',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Potencia de transmisión configurada (dBm).',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'location_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Ubicación física que cubre esta antena (dock door, frente de picking, etc).',
               existing_nullable=True)
    op.alter_column('rfid_antennas', 'antenna_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Número de puerto físico en el reader (1-N).',
               existing_nullable=False)
    op.drop_index(op.f('ix_labor_tasks_status'), table_name='labor_tasks')
    op.alter_column('labor_tasks', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('labor_tasks', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('labor_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('labor_tasks', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('labor_tasks', 'is_interleaved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='True si la tarea fue asignada por el motor de interleaving.')
    op.alter_column('labor_tasks', 'performance_pct',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               comment=None,
               existing_comment='standard/actual*100. 100 = cumple; >100 más rápido; <100 más lento.',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'standard_minutes',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Tiempo esperado según el estándar de ingeniería.',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'actual_minutes',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment=None,
               existing_comment='Tiempo real trabajado (completed_at - started_at).',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='pending | assigned | in_progress | completed | cancelled')
    op.alter_column('labor_tasks', 'uom',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('labor_tasks', 'quantity',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=True,
               comment=None,
               existing_comment='Unidades de trabajo (según uom del estándar).')
    op.alter_column('labor_tasks', 'priority',
               existing_type=sa.NUMERIC(precision=4, scale=0),
               nullable=True,
               comment=None,
               existing_comment='1 = más urgente … 9 = menos urgente.')
    op.alter_column('labor_tasks', 'zone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Código de zona para agrupar por proximidad.',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'reference_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='picking_task | putaway_task | grn | cycle_count | ...',
               existing_nullable=True)
    op.alter_column('labor_tasks', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Operario asignado. NULL mientras la tarea está en cola.',
               existing_nullable=True)
    op.alter_column('labor_standards', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('labor_standards', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('labor_standards', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('labor_standards', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('labor_standards', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('labor_standards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('labor_standards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('labor_standards', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('labor_standards', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('labor_standards', 'std_minutes_per_unit',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True,
               comment=None,
               existing_comment='Tiempo estándar por unidad de trabajo (minutos).')
    op.alter_column('labor_standards', 'fixed_minutes',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True,
               comment=None,
               existing_comment='Tiempo fijo de preparación/desplazamiento por tarea (minutos).')
    op.alter_column('labor_standards', 'uom',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='Unidad de medida del estándar: unit | line | case | pallet')
    op.alter_column('labor_standards', 'activity_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='pick | putaway | receive | pack | cycle_count | replenish | loading | unloading | transfer',
               existing_nullable=False)
    op.alter_column('labor_standards', 'warehouse_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Bodega a la que aplica. NULL = aplica a todo el tenant.',
               existing_nullable=True)
    op.alter_column('docks', 'tenant_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ID del tenant (empresa). Aislamiento de datos.',
               existing_nullable=False)
    op.alter_column('docks', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que hizo la ultima modificacion',
               existing_nullable=True)
    op.alter_column('docks', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='UUID del usuario que creo el registro',
               existing_nullable=True)
    op.alter_column('docks', 'deleted_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Usuario que elimino logicamente el registro',
               existing_nullable=True)
    op.alter_column('docks', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de eliminacion logica. NULL = activo.',
               existing_nullable=True)
    op.alter_column('docks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de ultima modificacion (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('docks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de creacion del registro (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('docks', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Identificador unico universal del registro',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('docks', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('docks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='available | occupied | maintenance | blocked')
    op.alter_column('docks', 'dock_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='receiving | shipping | both')
    op.drop_column('companies', 'logo_url')
    # ### end Alembic commands ###
